title: "Febria Anisaningrum"
email: febria.annisa@gmail.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/fevicon.ico'
author: Sal
paginate: 30
disqus: 'febriaanisa'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  febria:
    name: Febria Anisaningrum
    display_name: Febria Anisaningrum
    avatar: 'assets/images/febria.png'
    email: febria.annisa@gmail.com
    web: https://febriaanisa.github.io
    twitter: https://twitter.com/FebriaWangdu
    description: "Author of Febria blog."
  bondan:
    name: Bondan Murdani Soleh
    display_name: Bondan Murdani Soleh
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://bondan.my.id
    twitter: https://twitter.com/bondanhadoh
    description: "Ini adalah editor with Github pages."

# Social
social:
  instagram: https://www.instagram.com/febria.ann/
  facebook: https://www.facebook.com/febria.wangdu/
  twitter: https://twitter.com/FebriaWangdu

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
