title: "Febria Anisaningrum"
email: febria.annisa@gmail.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/fevicon.ico'
author: febria
paginate: 30
disqus: 'febriaanisa'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-JGR09RQHBN
    
google_site_verification: epGHsvrm3_3CNUQYLaogpVKOa95IqwaPlICCNoxLz8s
google_search_console:
       verification_file_code: 5de4167caaf2fe48
       
# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

#enable_google_analytics:    false  # enables google analytics
#enable_panelbear_analytics: false  # enables panelbear analytics
enable_google_verification: true   # enables google site verification
#enable_bing_verification:   true   # enables bing site verification
#enable_masonry:             false  # enables automatic project cards arangement
#enable_math:                true   # enables math typesetting (uses MathJax)
#enable_tooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
#enable_darkmode:            true   # enables switching between light/dark modes
#enable_navbar_social:       false  # enables displaying social links in the
                                   # navbar on the about page
#enable_project_categories:  false  # enables categorization of projects into
                                   # multiple categories
#enable_medium_zoom:         false  # enables image zoom feature (as on medium.com)


# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

# Authors
authors:
  febria:
    name: Febria Anisaningrum
    display_name: Febria Anisaningrum
    avatar: 'assets/images/febria.png'
    email: febria.annisa@gmail.com
    web: https://febriaanisa.github.io
    twitter: https://twitter.com/FebriaWangdu
    description: "Author of Febria blog."
  bondan:
    name: Bondan Murdani Soleh
    display_name: Bondan Murdani Soleh
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://bondan.my.id
    twitter: https://twitter.com/bondanhadoh
    description: "Ini adalah editor with Github pages."

# Social
social:
  instagram: https://www.instagram.com/febria.ann/
  facebook: https://www.facebook.com/febria.wangdu/
  twitter: https://twitter.com/FebriaWangdu

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-google-search-console-verification-file


defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "google5de4167caaf2fe48.html"]
